SASS-7859 - API for SBA
hmrc/income-tax-property pull request #26
Opened 2024-04-18 09:49 UTC by willjshark

2024-04-18 15:25 UTC, modivilioglu approved these changes
LGTM

2024-04-18 21:10 UTC, arunkumar461 commented
Journey name should be `SBA`

![image](https://github.com/hmrc/income-tax-property/assets/56151567/b8657948-851b-46d7-bbf6-9eac157ec103)

2024-04-18 21:12 UTC, arunkumar461 requested changes

2024-04-19 12:52 UTC, willjshark commented on conf/app.routes
> +PUT         /property/:taxYear/:businessId/income/:nino/:incomeSourceId/sba/answers                      controllers.JourneyAnswersController.updateSba(taxYear: TaxYear, businessId: BusinessId, nino:
Fixed

2024-04-19 13:27 UTC, modivilioglu commented on app/controllers/RequestHandler.scala
> +                                      journeyName: JourneyName,
Nice

2024-04-19 13:29 UTC, modivilioglu approved these changes
LGTM

2024-04-19 13:58 UTC, merged